# Setup
title:        Simon Bosman
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Simon Bosman
  url:        http://www.github.com/simonbosman 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-cayman
